---
version: '2'
services:
  proxy:
    build: ./
    networks:
    - site1
    - moodle
    - calibre
    - etherpad
    ports:
    - 80:80

networks:
  site1:
    external:
      name: site1_default
  moodle:
    external:
      name: moodle_default
  calibre:
    external:
      name: calibre-web
  etherpad:
    external:
      name: etherpad-net

